# NixOS module: services.tuntun-server
#
# Drop this into your NixOS configuration after importing
# `inputs.tuntun.nixosModules.tuntun-server`. The module:
#
# - runs `tuntun-server` as a systemd unit with Restart=on-failure and
#   exponential RestartSec backoff;
# - supervises Caddy as a managed subprocess (the daemon writes its own
#   Caddyfile and reloads Caddy when projects register/deregister);
# - opens the configured tunnel port (default 7000) in the firewall;
# - reads Porkbun credentials and the tenant secrets from
#   systemd LoadCredential entries (file paths supplied by the user, typically
#   from sops-nix / agenix / nix-sops).
#
# The actual binary is taken from `self.packages.${system}.tuntun-server` —
# the flake exposes it once `Cargo.lock` exists.

{ self }:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.tuntun-server;

  serverPkg =
    if cfg.package != null
    then cfg.package
    else
      let
        sysPkgs = self.packages.${pkgs.stdenv.hostPlatform.system} or { };
      in
      sysPkgs.tuntun-server or (throw ''
        services.tuntun-server: no `tuntun-server` package available for
        ${pkgs.stdenv.hostPlatform.system}. Either build the workspace
        (`cargo build -p tuntun_server` then re-evaluate) or set
        `services.tuntun-server.package` explicitly.
      '');

  tenantSubmodule = lib.types.submodule {
    options = {
      passwordHashFile = lib.mkOption {
        type = lib.types.path;
        description = ''
          Path on the running NixOS host to the Argon2id PHC-format password
          hash for this tenant's guests. Typically provisioned via sops-nix /
          agenix. Loaded via LoadCredential.
        '';
      };

      authorizedKeys = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [ "ed25519:AAAA..." ];
        description = ''
          Ed25519 public keys (in `ed25519:<base64>` form) of laptops allowed
          to open tunnels for this tenant. Generate with
          `scripts/regen-client-keys.rs` on the laptop side.
        '';
      };
    };
  };

  tenantsAuthorizedKeysJson = pkgs.writeText "tuntun-tenants.json" (
    builtins.toJSON (
      builtins.mapAttrs (_: t: { authorizedKeys = t.authorizedKeys; }) cfg.tenants
    )
  );

  configToml = pkgs.writeText "tuntun-server.toml" ''
    # Generated by services.tuntun-server NixOS module. Do not edit.

    domain = "${cfg.domain}"
    public_ip = "${cfg.publicIp}"
    tunnel_listen = "${cfg.tunnelListen}"
    auth_listen = "${cfg.authListen}"
    login_listen = "${cfg.loginListen}"
    state_dir = "${cfg.stateDir}"
    caddy_bin = "${pkgs.caddy}/bin/caddy"
    caddyfile_path = "${cfg.stateDir}/Caddyfile"
    caddy_admin = "${cfg.caddyAdmin}"
    caddy_log = "${cfg.stateDir}/caddy.log"
    acme_email = "${cfg.acmeEmail}"
    tenants_file = "${tenantsAuthorizedKeysJson}"
  '';
in
{
  options.services.tuntun-server = {
    enable = lib.mkEnableOption "tuntun reverse-tunnel server";

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = "The tuntun-server package to use. Defaults to the flake output.";
    };

    domain = lib.mkOption {
      type = lib.types.str;
      example = "memorici.de";
      description = "Apex domain this tuntun server serves subdomains under.";
    };

    publicIp = lib.mkOption {
      type = lib.types.str;
      example = "203.0.113.42";
      description = "IPv4 the apex/wildcard A record should resolve to.";
    };

    tunnelListen = lib.mkOption {
      type = lib.types.str;
      default = "0.0.0.0:7000";
      description = "host:port the tunnel listener (rustls + yamux) binds to.";
    };

    authListen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:7081";
      description = "host:port the internal forward_auth verifier binds to (Caddy talks to this).";
    };

    loginListen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:7090";
      description = "host:port the user-facing login HTTP service binds to (proxied by Caddy).";
    };

    stateDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/tuntun";
      description = "State directory: holds Caddyfile, server signing key, logs.";
    };

    caddyAdmin = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:2019";
      description = "Caddy admin endpoint (used by the daemon to trigger reloads).";
    };

    acmeEmail = lib.mkOption {
      type = lib.types.str;
      example = "ops@memorici.de";
      description = "Email registered with Let's Encrypt for ACME issuance.";
    };

    porkbun.apiKeyFile = lib.mkOption {
      type = lib.types.path;
      description = "Path to a file containing the Porkbun API key.";
    };

    porkbun.secretKeyFile = lib.mkOption {
      type = lib.types.path;
      description = "Path to a file containing the Porkbun secret key.";
    };

    serverSigningKeyFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Path to a PKCS#8 PEM file containing the server's long-term ed25519
        signing key (used to sign session-cookie tokens). If null, a key is
        generated on first start and persisted to ${cfg.stateDir}/server-signing-key.pem.
      '';
    };

    tenants = lib.mkOption {
      type = lib.types.attrsOf tenantSubmodule;
      default = { };
      description = "Tenant configuration: per-tenant authorized client keys + password hashes.";
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to open ${cfg.tunnelListen} in the NixOS firewall.";
    };

    extraEnvironment = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Extra env vars passed to the tuntun-server unit.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.tenants != { };
        message = "services.tuntun-server: at least one tenant must be defined.";
      }
    ];

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts = [
        80
        443
        (lib.toInt (lib.last (lib.splitString ":" cfg.tunnelListen)))
      ];
    };

    users.users.tuntun = {
      isSystemUser = true;
      group = "tuntun";
      home = cfg.stateDir;
      createHome = true;
    };
    users.groups.tuntun = { };

    systemd.tmpfiles.rules = [
      "d ${cfg.stateDir} 0750 tuntun tuntun -"
    ];

    # Caddy is supervised by tuntun-server itself, not by NixOS' services.caddy
    # — the daemon needs to rewrite the Caddyfile and trigger reloads.
    systemd.services.tuntun-server = {
      description = "tuntun reverse-tunnel server";
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      environment = {
        TUNTUN_CONFIG = "${configToml}";
        TUNTUN_STATE_DIR = cfg.stateDir;
        RUST_LOG = "info,tuntun_server=debug";
      } // cfg.extraEnvironment;

      serviceConfig = {
        Type = "notify";
        NotifyAccess = "all";
        ExecStart = "${serverPkg}/bin/tuntun-server run --config ${configToml}";
        User = "tuntun";
        Group = "tuntun";

        # Resilience defaults per CLAUDE.md rule 10.
        Restart = "on-failure";
        RestartSec = "2s";
        StartLimitBurst = 10;
        StartLimitIntervalSec = 60;

        # Hardening.
        ProtectSystem = "strict";
        ProtectHome = "yes";
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        NoNewPrivileges = true;
        RestrictRealtime = true;
        LockPersonality = true;
        ReadWritePaths = [ cfg.stateDir ];

        # Secrets via LoadCredential — the daemon reads them at
        # ${CREDENTIALS_DIRECTORY}/<name>.
        LoadCredential = [
          "porkbun-api-key:${cfg.porkbun.apiKeyFile}"
          "porkbun-secret-key:${cfg.porkbun.secretKeyFile}"
        ] ++ (lib.mapAttrsToList
          (tName: t: "tenant-password-${tName}:${t.passwordHashFile}")
          cfg.tenants)
        ++ (lib.optional (cfg.serverSigningKeyFile != null)
          "server-signing-key:${cfg.serverSigningKeyFile}");

        # Watchdog: server must sd_notify periodically.
        WatchdogSec = "30s";

        # Allow binding to 80/443 + the tunnel port.
        AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
        CapabilityBoundingSet = [ "CAP_NET_BIND_SERVICE" ];
      };
    };

    # Make `caddy` available on the system PATH so tuntun-server can spawn it.
    environment.systemPackages = [ pkgs.caddy serverPkg ];
  };
}
