# NixOS module: services.tuntun-server
#
# Drop this into your NixOS configuration after importing
# `inputs.tuntun.nixosModules.tuntun-server`. The module:
#
# - runs `tuntun-server` as a systemd unit with Restart=on-failure and
#   exponential RestartSec backoff;
# - supervises Caddy as a managed subprocess (the daemon writes its own
#   Caddyfile and reloads Caddy when projects register/deregister);
# - opens the configured tunnel port (default 7000) in the firewall;
# - reads Porkbun credentials and the tenant secrets from
#   systemd LoadCredential entries (file paths supplied by the user, typically
#   from sops-nix / agenix / nix-sops).
#
# The actual binary is taken from `self.packages.${system}.tuntun-server` —
# the flake exposes it once `Cargo.lock` exists.

{ self }:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.tuntun-server;

  serverPkg =
    if cfg.package != null
    then cfg.package
    else
      let
        sysPkgs = self.packages.${pkgs.stdenv.hostPlatform.system} or { };
      in
      sysPkgs.tuntun-server or (throw ''
        services.tuntun-server: no `tuntun-server` package available for
        ${pkgs.stdenv.hostPlatform.system}. Either build the workspace
        (`cargo build -p tuntun_server` then re-evaluate) or set
        `services.tuntun-server.package` explicitly.
      '');

  tenantSubmodule = lib.types.submodule {
    options = {
      passwordHashFile = lib.mkOption {
        type = lib.types.path;
        description = ''
          Path on the running NixOS host to the Argon2id PHC-format password
          hash for this tenant's guests. Typically provisioned via sops-nix /
          agenix. Loaded via LoadCredential.
        '';
      };

      authorizedKeys = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [ "ed25519:AAAA..." ];
        description = ''
          Ed25519 public keys (in `ed25519:<base64>` form) of laptops allowed
          to open tunnels for this tenant. Generate with
          `scripts/regen-client-keys.rs` on the laptop side.
        '';
      };
    };
  };

  tenantsAuthorizedKeysJson = pkgs.writeText "tuntun-tenants.json" (
    builtins.toJSON (
      builtins.mapAttrs (_: t: { authorizedKeys = t.authorizedKeys; }) cfg.tenants
    )
  );

  bastionSocket = "${cfg.stateDir}/bastion.sock";

  configToml = pkgs.writeText "tuntun-server.toml" ''
    # Generated by services.tuntun-server NixOS module. Do not edit.

    domain = "${cfg.domain}"
    public_ip = "${cfg.publicIp}"
    tunnel_listen = "${cfg.tunnelListen}"
    auth_listen = "${cfg.authListen}"
    login_listen = "${cfg.loginListen}"
    state_dir = "${cfg.stateDir}"
    caddy_bin = "${pkgs.caddy}/bin/caddy"
    caddyfile_path = "${cfg.stateDir}/Caddyfile"
    caddy_admin = "${cfg.caddyAdmin}"
    caddy_log = "${cfg.stateDir}/caddy.log"
    acme_email = "${cfg.acmeEmail}"
    tenants_file = "${tenantsAuthorizedKeysJson}"
    bastion_socket = "${bastionSocket}"
  '';

  # Script the bastion sshd's `AuthorizedKeysCommand` calls. It prints the
  # union of every tenant's authorized OpenSSH lines, each prefixed with a
  # locked-down `command="tuntun-server tcp-forward <tenant>"` clause so the
  # only thing OpenSSH lets that key do is invoke our forwarder for the
  # matching tenant. End-to-end SSH crypto is preserved because the bastion
  # only authenticates the *jump*; the inner SSH session is opaque.
  #
  # The `tuntun-keys-line` helper rewrites our `ed25519:<base64>` key format
  # into OpenSSH's `ssh-ed25519 <base64>` format, since that is what `sshd`
  # expects.
  # Render one OpenSSH `authorized_keys`-style line per (tenant, key). The
  # leading `command="..."` clause locks the key to a single, parameterless
  # invocation of our forwarder, so the bastion never sees the inner SSH
  # session. Tenant identity is bound to the *key*, not to the SSH username.
  formatBastionLine = tName: key:
    if lib.hasPrefix "ed25519:" key
    then
      let dropped = lib.removePrefix "ed25519:" key; in
      ''command="${serverPkg}/bin/tuntun-server tcp-forward ${tName}",no-pty,no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-user-rc ssh-ed25519 ${dropped} tuntun-bastion-${tName}''
    else
      # Pass-through for already-OpenSSH-formatted keys.
      ''command="${serverPkg}/bin/tuntun-server tcp-forward ${tName}",no-pty,no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-user-rc ${key}'';

  bastionAuthorizedKeysLines =
    lib.concatStringsSep "\n" (
      lib.flatten (
        lib.mapAttrsToList
          (tName: t: map (k: formatBastionLine tName k) t.authorizedKeys)
          cfg.tenants
      )
    );

  bastionAuthorizedKeysFile =
    pkgs.writeText "tuntun-bastion-authorized-keys" (
      bastionAuthorizedKeysLines + lib.optionalString (bastionAuthorizedKeysLines != "") "\n"
    );

  # OpenSSH's AuthorizedKeysCommand demands a single binary that prints the
  # authorized_keys lines on stdout. We hand it `cat <file>`.
  bastionAuthorizedKeysScript = pkgs.writeShellScript "tuntun-bastion-keys" ''
    exec ${pkgs.coreutils}/bin/cat ${bastionAuthorizedKeysFile}
  '';
in
{
  options.services.tuntun-server = {
    enable = lib.mkEnableOption "tuntun reverse-tunnel server";

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = "The tuntun-server package to use. Defaults to the flake output.";
    };

    domain = lib.mkOption {
      type = lib.types.str;
      example = "memorici.de";
      description = "Apex domain this tuntun server serves subdomains under.";
    };

    publicIp = lib.mkOption {
      type = lib.types.str;
      example = "203.0.113.42";
      description = "IPv4 the apex/wildcard A record should resolve to.";
    };

    tunnelListen = lib.mkOption {
      type = lib.types.str;
      default = "0.0.0.0:7000";
      description = "host:port the tunnel listener (rustls + yamux) binds to.";
    };

    authListen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:7081";
      description = "host:port the internal forward_auth verifier binds to (Caddy talks to this).";
    };

    loginListen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:7090";
      description = "host:port the user-facing login HTTP service binds to (proxied by Caddy).";
    };

    stateDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/tuntun";
      description = "State directory: holds Caddyfile, server signing key, logs.";
    };

    caddyAdmin = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:2019";
      description = "Caddy admin endpoint (used by the daemon to trigger reloads).";
    };

    acmeEmail = lib.mkOption {
      type = lib.types.str;
      example = "ops@memorici.de";
      description = "Email registered with Let's Encrypt for ACME issuance.";
    };

    porkbun.apiKeyFile = lib.mkOption {
      type = lib.types.path;
      description = "Path to a file containing the Porkbun API key.";
    };

    porkbun.secretKeyFile = lib.mkOption {
      type = lib.types.path;
      description = "Path to a file containing the Porkbun secret key.";
    };

    serverSigningKeyFile = lib.mkOption {
      type = lib.types.path;
      description = ''
        Path on the running host to a PKCS#8 PEM file containing the server's
        long-term ed25519 signing key. The daemon signs every session cookie
        with this key, so its identity is the trust anchor for every
        `forward_auth`-gated service. The file is read via systemd
        `LoadCredential` (so the daemon never sees the path directly).

        Generate via `rust-script -f scripts/regen-server-keys.rs` and
        scp the file to this path before deploying.
      '';
    };

    tenants = lib.mkOption {
      type = lib.types.attrsOf tenantSubmodule;
      default = { };
      description = "Tenant configuration: per-tenant authorized client keys + password hashes.";
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to open ${cfg.tunnelListen} in the NixOS firewall.";
    };

    extraEnvironment = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Extra env vars passed to the tuntun-server unit.";
    };

    ssh = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Whether to enable the reverse-SSH bastion side-car. When enabled,
          OpenSSH listens on `services.tuntun-server.ssh.bastionPort` in
          addition to its primary port; connections matching that port are
          dispatched (via `command="tuntun-server tcp-forward <tenant>"`
          forced commands) into the right tenant's tunnel and from there to
          the laptop's local sshd. The result is `ssh ssh.<tenant>.<domain>`
          UX with end-to-end SSH crypto preserved.
        '';
      };

      bastionPort = lib.mkOption {
        type = lib.types.port;
        default = 2222;
        description = ''
          TCP port the bastion listens on. Defaults to 2222 to leave port 22
          free for admin SSH; the home-manager module generates a
          `~/.ssh/config` block with the right `Port`, so users still type
          plain `ssh ssh.<tenant>.<domain>`.
        '';
      };

    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.tenants != { };
        message = "services.tuntun-server: at least one tenant must be defined.";
      }
    ];

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts = [
        80
        443
        (lib.toInt (lib.last (lib.splitString ":" cfg.tunnelListen)))
      ] ++ lib.optional cfg.ssh.enable cfg.ssh.bastionPort;
    };

    users.users.tuntun = {
      isSystemUser = true;
      group = "tuntun";
      home = cfg.stateDir;
      createHome = true;
      # OpenSSH refuses to run a session for a user whose shell is `nologin`
      # *unless* we override. The shell is never actually exec'd — the
      # `command="…"` clause in authorized_keys overrides it — but it must
      # be a real binary for sshd to admit the session.
      shell = lib.mkIf cfg.ssh.enable pkgs.bashInteractive;
    };
    users.groups.tuntun = { };

    systemd.tmpfiles.rules = [
      "d ${cfg.stateDir} 0750 tuntun tuntun -"
    ];

    # Caddy is supervised by tuntun-server itself, not by NixOS' services.caddy
    # — the daemon needs to rewrite the Caddyfile and trigger reloads.
    systemd.services.tuntun-server = {
      description = "tuntun reverse-tunnel server";
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      environment = {
        TUNTUN_CONFIG = "${configToml}";
        TUNTUN_STATE_DIR = cfg.stateDir;
        RUST_LOG = "info,tuntun_server=debug";
      } // cfg.extraEnvironment;

      # systemd 250+ wants StartLimit{Burst,IntervalSec} in [Unit], not
      # [Service]. Putting them under unitConfig is also the NixOS-native
      # spelling.
      unitConfig = {
        StartLimitBurst = 10;
        StartLimitIntervalSec = 60;
      };

      serviceConfig = {
        # `simple` instead of `notify` — we don't currently sd_notify, so
        # `notify` would put systemd in the strange position of treating an
        # otherwise-healthy long-running process as "not yet ready" forever.
        # Watchdog likewise off until we wire sd_notify pings.
        Type = "simple";
        ExecStart = "${serverPkg}/bin/tuntun-server run --config ${configToml}";
        User = "tuntun";
        Group = "tuntun";

        # Resilience defaults per CLAUDE.md rule 10.
        Restart = "on-failure";
        RestartSec = "2s";

        # Hardening.
        ProtectSystem = "strict";
        ProtectHome = "yes";
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        NoNewPrivileges = true;
        RestrictRealtime = true;
        LockPersonality = true;
        ReadWritePaths = [ cfg.stateDir ];

        # Secrets via LoadCredential — the daemon reads them at
        # ${CREDENTIALS_DIRECTORY}/<name>.
        LoadCredential = [
          "porkbun-api-key:${cfg.porkbun.apiKeyFile}"
          "porkbun-secret-key:${cfg.porkbun.secretKeyFile}"
          "server-signing-key:${cfg.serverSigningKeyFile}"
        ] ++ (lib.mapAttrsToList
          (tName: t: "tenant-password-${tName}:${t.passwordHashFile}")
          cfg.tenants);

        # Allow binding to 80/443 + the tunnel port.
        AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
        CapabilityBoundingSet = [ "CAP_NET_BIND_SERVICE" ];
      };
    };

    # Make `caddy` available on the system PATH so tuntun-server can spawn it.
    environment.systemPackages = [ pkgs.caddy serverPkg ];

    # SSH bastion side-car. We attach to the existing `services.openssh`
    # instance via `ports` and a `Match LocalPort` block — running a second
    # sshd would be cleaner in isolation but harder to reason about under
    # NixOS' module merging. The Match block scopes our forced-command
    # behavior to bastion-port connections only; admin SSH on port 22 is
    # untouched.
    services.openssh = lib.mkIf cfg.ssh.enable {
      enable = lib.mkDefault true;
      ports = [ 22 cfg.ssh.bastionPort ];
      extraConfig = ''
        Match LocalPort ${toString cfg.ssh.bastionPort} User tuntun
            AuthorizedKeysFile none
            AuthorizedKeysCommand ${bastionAuthorizedKeysScript}
            AuthorizedKeysCommandUser tuntun
            PasswordAuthentication no
            KbdInteractiveAuthentication no
            PermitTTY no
            X11Forwarding no
            AllowTcpForwarding no
            AllowAgentForwarding no
            PermitOpen none
        Match all
      '';
    };
  };
}
