//! Argon2id password hashing and verification.
//!
//! Parameters per workspace policy (CLAUDE.md rule 5): `m_cost = 19_456`,
//! `t_cost = 2`, `p_cost = 1`. PHC-format strings only — never raw hash bytes.
//!
//! This module is pure: salt is supplied by the caller (binary crates generate
//! it via `OsRng`); we never touch the system RNG here.

use std::fmt;

use argon2::password_hash::{PasswordHash, PasswordHasher, PasswordVerifier, SaltString};
use argon2::{Algorithm, Argon2, Params, Version};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tuntun_core::Error as CoreError;
use zeroize::Zeroize;

/// Argon2id memory cost in 1 KiB blocks.
pub const ARGON2_M_COST: u32 = 19_456;
/// Argon2id iteration count.
pub const ARGON2_T_COST: u32 = 2;
/// Argon2id parallelism.
pub const ARGON2_P_COST: u32 = 1;

/// 16-byte random salt. Generated by binary crates via `OsRng`; library code
/// only consumes it.
#[derive(Clone, Copy, Zeroize)]
pub struct Salt(pub [u8; 16]);

impl Salt {
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

impl fmt::Debug for Salt {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Salts are not exactly secret, but they are not interesting to log
        // either. Redact for consistency with other crypto types.
        f.write_str("Salt(<redacted>)")
    }
}

/// PHC-format Argon2id password hash, e.g.
/// `$argon2id$v=19$m=19456,t=2,p=1$<salt-b64>$<hash-b64>`.
///
/// Serializes transparently as a string so it round-trips through JSON / TOML
/// just like a `String`.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PasswordHashPhc(String);

impl PasswordHashPhc {
    /// Wrap an existing PHC string. Validates that it parses as a valid
    /// password hash, but does not check the algorithm or parameters.
    pub fn parse(s: impl Into<String>) -> Result<Self, PasswordError> {
        let s = s.into();
        // Validate by trying to parse — we discard the result, but this rejects
        // malformed inputs early.
        PasswordHash::new(&s).map_err(|e| PasswordError::InvalidPhc(e.to_string()))?;
        Ok(Self(s))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for PasswordHashPhc {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // The PHC string contains the hash output; redact it. The salt and
        // params are public information, but combined with the hash they form
        // an offline-attackable record.
        f.write_str("PasswordHashPhc(<redacted>)")
    }
}

impl fmt::Display for PasswordHashPhc {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

#[derive(Debug, Error)]
pub enum PasswordError {
    #[error("argon2 parameters: {0}")]
    Params(String),
    #[error("argon2 hashing: {0}")]
    Hashing(String),
    #[error("argon2 verification failed")]
    VerificationFailed,
    #[error("invalid PHC string: {0}")]
    InvalidPhc(String),
}

impl From<PasswordError> for CoreError {
    fn from(value: PasswordError) -> Self {
        CoreError::auth(value.to_string())
    }
}

fn argon2_with_policy() -> Result<Argon2<'static>, PasswordError> {
    let params = Params::new(ARGON2_M_COST, ARGON2_T_COST, ARGON2_P_COST, None)
        .map_err(|e| PasswordError::Params(e.to_string()))?;
    Ok(Argon2::new(Algorithm::Argon2id, Version::V0x13, params))
}

/// Hash a password using Argon2id with workspace-mandated parameters.
///
/// Pure: caller supplies the salt. Returns a PHC-format string that captures
/// the algorithm, version, parameters, salt, and hash output.
pub fn hash_password(password: &[u8], salt: &Salt) -> Result<PasswordHashPhc, PasswordError> {
    let argon = argon2_with_policy()?;
    let salt_string =
        SaltString::encode_b64(salt.as_bytes()).map_err(|e| PasswordError::Params(e.to_string()))?;
    let phc = argon
        .hash_password(password, &salt_string)
        .map_err(|e| PasswordError::Hashing(e.to_string()))?
        .to_string();
    Ok(PasswordHashPhc(phc))
}

/// Verify a password against a stored PHC hash. Constant time.
///
/// Returns `Ok(())` on match, [`PasswordError::VerificationFailed`] otherwise.
pub fn verify_password(hash: &PasswordHashPhc, password: &[u8]) -> Result<(), PasswordError> {
    let parsed =
        PasswordHash::new(hash.as_str()).map_err(|e| PasswordError::InvalidPhc(e.to_string()))?;
    let argon = argon2_with_policy()?;
    argon
        .verify_password(password, &parsed)
        .map_err(|_| PasswordError::VerificationFailed)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixed_salt() -> Salt {
        Salt::from_bytes([0x42; 16])
    }

    #[test]
    fn hash_and_verify_round_trip() {
        let salt = fixed_salt();
        let hash = hash_password(b"correct horse battery staple", &salt).expect("hash");
        verify_password(&hash, b"correct horse battery staple").expect("verify");
    }

    #[test]
    fn verify_rejects_wrong_password() {
        let salt = fixed_salt();
        let hash = hash_password(b"swordfish", &salt).expect("hash");
        let err = verify_password(&hash, b"hunter2").unwrap_err();
        assert!(matches!(err, PasswordError::VerificationFailed));
    }

    #[test]
    fn hashes_with_same_salt_are_deterministic() {
        let salt = fixed_salt();
        let a = hash_password(b"pw", &salt).expect("a");
        let b = hash_password(b"pw", &salt).expect("b");
        assert_eq!(a, b);
    }

    #[test]
    fn hashes_with_different_salts_differ() {
        let a = hash_password(b"pw", &Salt::from_bytes([1u8; 16])).expect("a");
        let b = hash_password(b"pw", &Salt::from_bytes([2u8; 16])).expect("b");
        assert_ne!(a, b);
    }

    #[test]
    fn phc_string_advertises_required_parameters() {
        let salt = fixed_salt();
        let hash = hash_password(b"pw", &salt).expect("hash");
        let s = hash.as_str();
        assert!(s.starts_with("$argon2id$"), "got: {s}");
        assert!(s.contains("m=19456"), "got: {s}");
        assert!(s.contains("t=2"), "got: {s}");
        assert!(s.contains("p=1"), "got: {s}");
    }

    #[test]
    fn empty_password_round_trip() {
        let salt = fixed_salt();
        let hash = hash_password(b"", &salt).expect("hash");
        verify_password(&hash, b"").expect("verify");
        assert!(verify_password(&hash, b"x").is_err());
    }

    #[test]
    fn long_password_round_trip() {
        let salt = fixed_salt();
        let pw = vec![b'q'; 1024];
        let hash = hash_password(&pw, &salt).expect("hash");
        verify_password(&hash, &pw).expect("verify");
    }

    #[test]
    fn parse_round_trip() {
        let salt = fixed_salt();
        let hash = hash_password(b"pw", &salt).expect("hash");
        let s = hash.to_string();
        let back = PasswordHashPhc::parse(s.clone()).expect("parse");
        assert_eq!(back.as_str(), s);
    }

    #[test]
    fn parse_rejects_garbage() {
        assert!(PasswordHashPhc::parse("not a phc string").is_err());
    }

    #[test]
    fn debug_redacts_hash() {
        let salt = fixed_salt();
        let hash = hash_password(b"pw", &salt).expect("hash");
        let dbg = format!("{hash:?}");
        assert_eq!(dbg, "PasswordHashPhc(<redacted>)");
    }

    #[test]
    fn debug_redacts_salt() {
        let salt = Salt::from_bytes([0xAB; 16]);
        assert_eq!(format!("{salt:?}"), "Salt(<redacted>)");
    }

    #[test]
    fn serde_round_trip_through_json() {
        let salt = fixed_salt();
        let hash = hash_password(b"pw", &salt).expect("hash");
        let json = serde_json::to_string(&hash).expect("ser");
        let back: PasswordHashPhc = serde_json::from_str(&json).expect("de");
        assert_eq!(back, hash);
    }

    #[test]
    fn core_error_conversion() {
        let err: CoreError = PasswordError::VerificationFailed.into();
        let msg = err.to_string();
        assert!(msg.contains("auth"), "got: {msg}");
    }
}
