//! Public-key and signature value types. The actual crypto computations live
//! in `tuntun_auth` — this module just defines the data types crossing port
//! boundaries.

use std::fmt;

use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq;

use crate::error::Error;

/// Ed25519 public key, 32 bytes.
#[derive(Clone, Copy, Serialize, Deserialize)]
pub struct Ed25519PublicKey(pub [u8; 32]);

impl Ed25519PublicKey {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Parse from a textual `ed25519:<base64>` representation.
    pub fn from_authorized_keys_line(line: &str) -> Result<Self, Error> {
        let trimmed = line.trim();
        let body = trimmed
            .strip_prefix("ed25519:")
            .ok_or_else(|| Error::crypto("authorized key missing ed25519: prefix"))?;
        let bytes = base64_decode(body)
            .map_err(|e| Error::crypto(format!("authorized key not base64: {e}")))?;
        if bytes.len() != 32 {
            return Err(Error::crypto(format!(
                "authorized key wrong length: {} (expected 32)",
                bytes.len()
            )));
        }
        let mut out = [0u8; 32];
        out.copy_from_slice(&bytes);
        Ok(Self(out))
    }

    pub fn to_authorized_keys_line(self) -> String {
        format!("ed25519:{}", base64_encode(&self.0))
    }
}

impl fmt::Debug for Ed25519PublicKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Ed25519PublicKey({})", hex::encode(self.0))
    }
}

impl PartialEq for Ed25519PublicKey {
    fn eq(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }
}

impl Eq for Ed25519PublicKey {}

impl std::hash::Hash for Ed25519PublicKey {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

/// Ed25519 signature, 64 bytes.
#[derive(Clone, Copy, Serialize, Deserialize)]
pub struct Ed25519Signature(#[serde(with = "serde_arrays_64")] pub [u8; 64]);

impl fmt::Debug for Ed25519Signature {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Ed25519Signature({}...)", hex::encode(&self.0[..8]))
    }
}

impl PartialEq for Ed25519Signature {
    fn eq(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }
}

impl Eq for Ed25519Signature {}

/// SHA-256 fingerprint, 32 bytes.
#[derive(Clone, Copy, Serialize, Deserialize)]
pub struct Fingerprint(pub [u8; 32]);

impl Fingerprint {
    pub fn from_hex(s: &str) -> Result<Self, Error> {
        let s = s.strip_prefix("sha256:").unwrap_or(s);
        let bytes = hex::decode(s).map_err(|e| Error::crypto(format!("hex: {e}")))?;
        if bytes.len() != 32 {
            return Err(Error::crypto(format!(
                "fingerprint wrong length: {} (expected 32)",
                bytes.len()
            )));
        }
        let mut out = [0u8; 32];
        out.copy_from_slice(&bytes);
        Ok(Self(out))
    }

    pub fn to_hex_with_prefix(self) -> String {
        format!("sha256:{}", hex::encode(self.0))
    }
}

impl fmt::Debug for Fingerprint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Fingerprint({})", self.to_hex_with_prefix())
    }
}

impl PartialEq for Fingerprint {
    fn eq(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }
}

impl Eq for Fingerprint {}

/// Random nonce, 32 bytes. Generated by binaries; library code only verifies.
#[derive(Clone, Copy, Serialize, Deserialize)]
pub struct Nonce(pub [u8; 32]);

impl Nonce {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }
}

impl fmt::Debug for Nonce {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Nonce({})", hex::encode(self.0))
    }
}

impl PartialEq for Nonce {
    fn eq(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }
}

impl Eq for Nonce {}

mod serde_arrays_64 {
    use serde::{de::Error as _, Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(arr: &[u8; 64], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_bytes(arr)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<[u8; 64], D::Error> {
        let v = Vec::<u8>::deserialize(d)?;
        if v.len() != 64 {
            return Err(D::Error::custom(format!(
                "expected 64 bytes, got {}",
                v.len()
            )));
        }
        let mut out = [0u8; 64];
        out.copy_from_slice(&v);
        Ok(out)
    }
}

fn base64_encode(bytes: &[u8]) -> String {
    use base64::engine::general_purpose::STANDARD_NO_PAD;
    use base64::Engine as _;
    STANDARD_NO_PAD.encode(bytes)
}

fn base64_decode(s: &str) -> Result<Vec<u8>, base64::DecodeError> {
    use base64::engine::general_purpose::STANDARD_NO_PAD;
    use base64::Engine as _;
    STANDARD_NO_PAD.decode(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pubkey_authorized_keys_round_trip() {
        let key = Ed25519PublicKey::from_bytes([7u8; 32]);
        let line = key.to_authorized_keys_line();
        assert!(line.starts_with("ed25519:"));
        let back = Ed25519PublicKey::from_authorized_keys_line(&line).unwrap();
        assert_eq!(key, back);
    }

    #[test]
    fn fingerprint_round_trip() {
        let fp = Fingerprint([42u8; 32]);
        let s = fp.to_hex_with_prefix();
        assert!(s.starts_with("sha256:"));
        let back = Fingerprint::from_hex(&s).unwrap();
        assert_eq!(fp, back);
    }

    #[test]
    fn fingerprint_rejects_wrong_length() {
        assert!(Fingerprint::from_hex("ab").is_err());
    }
}
