//! `tuntun-server tcp-forward <tenant>` -- bastion sshd `ForceCommand` helper.
//!
//! OpenSSH invokes this binary when an SSH client authenticates against the
//! bastion port using a key tied to a specific tenant (the binding is set up
//! via the `command="tuntun-server tcp-forward <tenant>"` prefix in
//! `authorized_keys`, generated by the NixOS module).
//!
//! The helper connects to the running daemon's unix-domain socket, writes a
//! short header line `tenant=<id>\n`, and then pipes its stdin/stdout to the
//! socket — which the daemon, on the other side, forwards through the
//! tenant's tunnel into the laptop's local sshd. End-to-end SSH crypto is
//! preserved because the bastion only authenticates the *jump*; it never
//! decodes the inner SSH session.
//!
//! This subcommand performs no auth of its own — that's already happened at
//! the bastion sshd layer. It is a deliberately minimal pipe.

use std::path::Path;

use anyhow::{anyhow, Context, Result};
use tokio::io::{AsyncWriteExt, BufWriter};
use tokio::net::UnixStream;

use tuntun_core::TenantId;

use crate::config::ServerConfig;

pub async fn run(config: Option<&Path>, tenant: &str) -> Result<()> {
    // Validate the tenant id. We don't trust argv even though the bastion
    // wrote it: a misconfigured authorized_keys line would otherwise let a
    // tenant hijack another's tunnel.
    let tenant = TenantId::new(tenant.to_string())
        .map_err(|e| anyhow!("invalid tenant id: {e}"))?;

    let cfg = ServerConfig::load(config).await?;
    let socket = cfg.bastion_socket.clone();

    let sock = UnixStream::connect(&socket)
        .await
        .with_context(|| format!("connect bastion socket {}", socket.display()))?;
    let (mut sock_read, sock_write) = sock.into_split();
    let mut sock_write = BufWriter::new(sock_write);

    // Send the header line first.
    let header = format!("tenant={tenant}\n");
    sock_write
        .write_all(header.as_bytes())
        .await
        .context("write bastion header")?;
    sock_write.flush().await.context("flush bastion header")?;

    // Pipe stdio in both directions concurrently. We cannot use
    // `tokio::io::copy_bidirectional` here because stdin/stdout are *not* a
    // single duplex stream — they are two unidirectional handles.
    let mut stdin = tokio::io::stdin();
    let mut stdout = tokio::io::stdout();

    let up = async {
        let r = tokio::io::copy(&mut stdin, &mut sock_write).await;
        // Half-shutdown so the laptop's sshd sees stdin EOF.
        let _ = sock_write.shutdown().await;
        r
    };
    let down = async { tokio::io::copy(&mut sock_read, &mut stdout).await };

    let (up_res, down_res) = tokio::join!(up, down);
    up_res.context("pipe stdin -> bastion")?;
    down_res.context("pipe bastion -> stdout")?;
    Ok(())
}
